# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJl < Formula
  desc "Show the `JSON within JSON` log nicely"
  homepage "https://github.com/bayashi/go-jl"
  version "1.3.4"

  on_macos do
    on_intel do
      url "https://github.com/bayashi/go-jl/releases/download/v1.3.4/go-jl_1.3.4_darwin_amd64.tar.gz"
      sha256 "3241ff982c5d43640922c937dda338c278e8d40a57e8bf5039a9057af69afbcd"

      def install
        bin.install "jl"
      end
    end
    on_arm do
      url "https://github.com/bayashi/go-jl/releases/download/v1.3.4/go-jl_1.3.4_darwin_arm64.tar.gz"
      sha256 "14bcfb10a7c403eb1698b72b4378c9664075ba6d5d82ad94ea0a412ab0912f7d"

      def install
        bin.install "jl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/go-jl/releases/download/v1.3.4/go-jl_1.3.4_linux_amd64.tar.gz"
        sha256 "4e174d632e46d1dc750f853b92356ee1f2c34eae786b6f2b1fbaeefa716faafe"

        def install
          bin.install "jl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/go-jl/releases/download/v1.3.4/go-jl_1.3.4_linux_arm64.tar.gz"
        sha256 "08cd4cb84223a5cf88d6b5fe18b0a6d91836fe4c3723dc0f18b54fa5ec0ef52d"

        def install
          bin.install "jl"
        end
      end
    end
  end

  test do
    system "#{bin}/jl", '--version'
  end
end
