# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJl < Formula
  desc "Show the `JSON within JSON` log nicely"
  homepage "https://github.com/bayashi/go-jl"
  version "1.4.0"

  on_macos do
    on_intel do
      url "https://github.com/bayashi/go-jl/releases/download/v1.4.0/go-jl_1.4.0_darwin_amd64.tar.gz"
      sha256 "d19cfb597c874de8394dc701f3e7edd27669d9e45b59a5fe411535e03c5c5a58"

      def install
        bin.install "jl"
      end
    end
    on_arm do
      url "https://github.com/bayashi/go-jl/releases/download/v1.4.0/go-jl_1.4.0_darwin_arm64.tar.gz"
      sha256 "69ef963453e057aa9ae70d28b095749eee8362222986cbd5d75f6e5ba42fe13d"

      def install
        bin.install "jl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/go-jl/releases/download/v1.4.0/go-jl_1.4.0_linux_amd64.tar.gz"
        sha256 "20990101b1536ca6e0e24397e091f24e13c65cd51505d9320f957108210d5e35"

        def install
          bin.install "jl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/go-jl/releases/download/v1.4.0/go-jl_1.4.0_linux_arm64.tar.gz"
        sha256 "fc51a77d610fef444e2caf81f778bdc4efb191a10720aa00b65f72b33e7b9b1c"

        def install
          bin.install "jl"
        end
      end
    end
  end

  test do
    system "#{bin}/jl", '--version'
  end
end
