# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoVl < Formula
  desc "Makes CUI table vertical"
  homepage "https://github.com/bayashi/go-vl"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bayashi/go-vl/releases/download/v0.0.1/go-vl_0.0.1_darwin_arm64.tar.gz"
      sha256 "3602d8ed18c9d24e7eaec8653533438a6ffcc6fa49abb8f9fda3c352dfd8ea6d"

      def install
        bin.install "vl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/go-vl/releases/download/v0.0.1/go-vl_0.0.1_darwin_amd64.tar.gz"
      sha256 "40a555e77649daf01c71dc61097c657f59fa5a9bfccdaef6baf742d70e3c9f69"

      def install
        bin.install "vl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bayashi/go-vl/releases/download/v0.0.1/go-vl_0.0.1_linux_arm64.tar.gz"
      sha256 "9d0bd46e908427dc33b93a2e01aec0ee14dac4aeebfdb20248f6338ac7101756"

      def install
        bin.install "vl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/go-vl/releases/download/v0.0.1/go-vl_0.0.1_linux_amd64.tar.gz"
      sha256 "a53d2b76c15c5ff1a93fe0fe705c5e0cae8884737faead249dd216646b958472"

      def install
        bin.install "vl"
      end
    end
  end

  test do
    system "#{bin}/vl", '--version'
  end
end
