# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goverview < Formula
  desc "Display an overview as ASCII tree for a Golang project"
  homepage "https://github.com/bayashi/goverview"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bayashi/goverview/releases/download/v0.4.3/goverview_0.4.3_darwin_arm64.tar.gz"
      sha256 "d4ad1262e06a2ddd5d945638a0613185f566fcffe199142ef298fca75ba6c464"

      def install
        bin.install "goverview"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/goverview/releases/download/v0.4.3/goverview_0.4.3_darwin_amd64.tar.gz"
      sha256 "fdd8c112ba7d99eaa58a760d58b16a370043c09f0baeeef800d4a1d203e3d237"

      def install
        bin.install "goverview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/goverview/releases/download/v0.4.3/goverview_0.4.3_linux_amd64.tar.gz"
      sha256 "855bddbf3eeee2dc9eb91c8def9faf023e713f16386391e2478950539dddc5bb"

      def install
        bin.install "goverview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bayashi/goverview/releases/download/v0.4.3/goverview_0.4.3_linux_arm64.tar.gz"
      sha256 "6d52527284b44cd3cd81313a957263b322b1eda7b8ec1866c1f709f0dfc8a4b5"

      def install
        bin.install "goverview"
      end
    end
  end

  test do
    system "#{bin}/goverview", '--version'
  end
end
