# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Highlightrepo < Formula
  desc "highlightrepo provides a filter to highlight repository directory in a path string."
  homepage "https://github.com/bayashi/highlightrepo"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/highlightrepo/releases/download/v0.0.1/highlightrepo_0.0.1_darwin_amd64.tar.gz"
      sha256 "7b00c5764f883f34ed8c814994dde20a9b7c108bb50ec2310a00e76b2c468778"

      def install
        bin.install "irir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bayashi/highlightrepo/releases/download/v0.0.1/highlightrepo_0.0.1_darwin_arm64.tar.gz"
      sha256 "406205a75291299d3a4f9b3baf4e8e3cce492b4d8ef33024c9096dc6e898535c"

      def install
        bin.install "irir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/highlightrepo/releases/download/v0.0.1/highlightrepo_0.0.1_linux_amd64.tar.gz"
      sha256 "fd42f7311a580ce2b795a6dcc3e204f7728a8d2d016947032731ac3402cb948e"

      def install
        bin.install "irir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bayashi/highlightrepo/releases/download/v0.0.1/highlightrepo_0.0.1_linux_arm64.tar.gz"
      sha256 "342cb90fe457d5ab83ff0b68a0112c0381a057021f0f5bbb75fa0c5f6474d892"

      def install
        bin.install "irir"
      end
    end
  end

  test do
    system "#{bin}/highlightrepo", '--version'
  end
end
