# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Irir < Formula
  desc "A filter to add colors for text lines generically from a YAML configuration file easily"
  homepage "https://github.com/bayashi/irir"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bayashi/irir/releases/download/v0.5.0/irir_0.5.0_darwin_arm64.tar.gz"
      sha256 "84572eadb0772cb0827209bba930996449f5c9952f8e78b39c37eb81df91a2cb"

      def install
        bin.install "irir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/irir/releases/download/v0.5.0/irir_0.5.0_darwin_amd64.tar.gz"
      sha256 "2e4ce4524407f6d52cbe461cb059f529d1a58a8ffff089ed3d81fd2cae6d0690"

      def install
        bin.install "irir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bayashi/irir/releases/download/v0.5.0/irir_0.5.0_linux_arm64.tar.gz"
      sha256 "d1465a708bfe330f9c8f46fe08cc17bf09246e9fc33407bf189056232c805848"

      def install
        bin.install "irir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bayashi/irir/releases/download/v0.5.0/irir_0.5.0_linux_amd64.tar.gz"
      sha256 "0ab4e5d3198a1f300dc6b694dc34a0bf3cb63cf97929fadf543062112e41a5bb"

      def install
        bin.install "irir"
      end
    end
  end

  test do
    system "#{bin}/irir", '--version'
  end
end
