# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qq < Formula
  desc "References of Quick Questions"
  homepage "https://github.com/bayashi/qq"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/bayashi/qq/releases/download/v0.0.5/qq_0.0.5_darwin_amd64.tar.gz"
      sha256 "9be3ddaa55e0867627a8a776134bdc8b349fef2435106412833b98821d1a6545"

      def install
        bin.install "qq"
      end
    end
    on_arm do
      url "https://github.com/bayashi/qq/releases/download/v0.0.5/qq_0.0.5_darwin_arm64.tar.gz"
      sha256 "d0dbcb4ddc57b9a8fed97b1d0f0de0698e85dc0b944d6c885418271a96e4aed8"

      def install
        bin.install "qq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.5/qq_0.0.5_linux_amd64.tar.gz"
        sha256 "ba96602d9cdc389bcd733956a571361d273cccdede16ac7b3dc2b2303490c970"

        def install
          bin.install "qq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.5/qq_0.0.5_linux_arm64.tar.gz"
        sha256 "4ec3a27ba3f3800724c7c8cdcfb8142e0d0d328a1a0daeb242d8785465e34d4c"

        def install
          bin.install "qq"
        end
      end
    end
  end

  test do
    system "#{bin}/qq", '--version'
  end
end
