# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qq < Formula
  desc "References of Quick Questions"
  homepage "https://github.com/bayashi/qq"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/bayashi/qq/releases/download/v0.0.4/qq_0.0.4_darwin_amd64.tar.gz"
      sha256 "e3bb97a8967ea07e36a08536af0ca7082c691009baf413bb00a62768a9fc0334"

      def install
        bin.install "qq"
      end
    end
    on_arm do
      url "https://github.com/bayashi/qq/releases/download/v0.0.4/qq_0.0.4_darwin_arm64.tar.gz"
      sha256 "3259481dbc0855b4ab620631134fdac3497e688586ea34e085ed04a9dd802aef"

      def install
        bin.install "qq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.4/qq_0.0.4_linux_amd64.tar.gz"
        sha256 "fa6c8c801c984d5c0651f3366147d88e39659c10ec404f96c22e844421937142"

        def install
          bin.install "qq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.4/qq_0.0.4_linux_arm64.tar.gz"
        sha256 "b741ab838270ed3f0d998d2f004d0740ff38310152ade3b807c726ce53343e10"

        def install
          bin.install "qq"
        end
      end
    end
  end

  test do
    system "#{bin}/qq", '--version'
  end
end
