# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qq < Formula
  desc "References of Quick Questions"
  homepage "https://github.com/bayashi/qq"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/bayashi/qq/releases/download/v0.0.3/qq_0.0.3_darwin_amd64.tar.gz"
      sha256 "384dff63fb15a84805956039781dc20750a534b9955a09f4331cdf94450f9e23"

      def install
        bin.install "qq"
      end
    end
    on_arm do
      url "https://github.com/bayashi/qq/releases/download/v0.0.3/qq_0.0.3_darwin_arm64.tar.gz"
      sha256 "bd3574483fec7ccb154770d92ade848a2d414699baf8732eef917ad6f5a51716"

      def install
        bin.install "qq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.3/qq_0.0.3_linux_amd64.tar.gz"
        sha256 "224dc199fbdf863c0e8e4825da0a93e094c6ab970c95ec7cfe1a0b4a7f367189"

        def install
          bin.install "qq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bayashi/qq/releases/download/v0.0.3/qq_0.0.3_linux_arm64.tar.gz"
        sha256 "abda39faaf2392dacc838d100b5d5b26410860debb6a57e22117e5613c91adc2"

        def install
          bin.install "qq"
        end
      end
    end
  end

  test do
    system "#{bin}/qq", '--version'
  end
end
